# Generated by Django 6.0.4 on 2026-06-17 21:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_userprofile_is_admin_course_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_instructor_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_overall_admin',
        ),
        migrations.AddField(
            model_name='accesscode',
            name='access_type',
            field=models.CharField(choices=[('student', 'Student Access'), ('instructor', 'Instructor Access'), ('super_admin', 'Super Admin Access')], default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='accesscode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesscode',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='portal.course'),
        ),
        migrations.AddField(
            model_name='user',
            name='instructor_courses',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='portal.course'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('instructor', 'Instructor'), ('student', 'Student')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.course'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
