# Generated by Django 6.0.4 on 2026-06-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_create_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscode',
            name='access_type',
            field=models.CharField(choices=[('instructor', 'Instructor Access'), ('student', 'Student Access')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
