# Generated by Django 6.0.4 on 2026-07-08 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_status_from_is_approved(apps, schema_editor):
    """Preserve existing approval state: any submission that was already
    approved under the old boolean field becomes status='approved';
    everything else stays 'pending' (the new default)."""
    Submission = apps.get_model('portal', 'Submission')
    Submission.objects.filter(is_approved=True).update(status='approved')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_surveyquestion_alter_user_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='instructor_note',
            field=models.TextField(blank=True, help_text='Optional note shown to the student, e.g. why it was rejected.'),
        ),
        migrations.AddField(
            model_name='submission',
            name='instructor_score',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank to use the auto-computed score. Set this to override it before approving.', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        # Data migration: copy old is_approved boolean into the new status
        # field BEFORE the column is dropped below.
        migrations.RunPython(backfill_status_from_is_approved, noop_reverse),
        migrations.RemoveField(
            model_name='submission',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('text', 'Text (exact match)'), ('mcq', 'Multiple Choice'), ('true_false', 'True / False')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='correct_answer',
            field=models.CharField(blank=True, help_text="Used for 'Text' type (exact match, case-insensitive) and 'True/False' type (enter True or False). Not used for Multiple Choice -- add options below instead.", max_length=500),
        ),
        migrations.CreateModel(
            name='AssignedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('resource_link', models.URLField(blank=True, help_text='Optional reference link for the student to read first, e.g. a Google Drive PDF.')),
                ('submission_link', models.URLField(blank=True, help_text="The student's submitted link.")),
                ('status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('submitted', 'Submitted - Awaiting Review'), ('approved', 'Approved'), ('rejected', 'Rejected - Needs Resubmission')], default='not_submitted', max_length=20)),
                ('instructor_note', models.TextField(blank=True, help_text='Optional note shown to the student, e.g. why it was rejected.')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='portal.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks_given', to=settings.AUTH_USER_MODEL)),
                ('required_playlist', models.ForeignKey(blank=True, help_text="If set, this task only appears on the student's dashboard once every lesson in this playlist is completed. Leave blank for no prerequisite.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gated_assigned_tasks', to='portal.playlist')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='portal.task')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
