# Generated by Django 6.0.4 on 2026-07-08 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_task_types_assigned_tasks_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='required_lesson_count',
            field=models.PositiveIntegerField(blank=True, help_text='How many lessons in the required playlist must be completed before this task becomes visible. Only used if a required playlist is set above.', null=True),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='required_playlist',
            field=models.ForeignKey(blank=True, help_text="If set, this task only appears on the student's dashboard once the student has completed at least 'Required lesson count' lessons in this playlist. Leave blank for no prerequisite.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gated_assigned_tasks', to='portal.playlist'),
        ),
    ]
