# Generated by Django 6.0.4 on 2026-07-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_backfill_survey_response_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='score',
            field=models.PositiveIntegerField(blank=True, help_text='Score out of 100, set by the instructor when approving. Optional.', null=True),
        ),
    ]
